apiVersion: v1
kind: Pod
metadata:
  name: test1-nginx-img-old
  namespace: nginx
  labels:
    app: nginx
spec:
  restartPolicy: OnFailure
  containers:
    - name: test1
      image: nginx:1.17.1
      imagePullPolicy: Always