apiVersion: v1
kind: Pod
metadata:
  name: test3-non-nginx-img
  namespace: nginx
  labels:
    app: redis
spec:
  restartPolicy: OnFailure
  containers:
    - name: test3
      image: redis
      imagePullPolicy: Always