apiVersion: v1
kind: Pod
metadata:
  name: test5-nginx-img-default-ns
  namespace: default
  labels:
    app: nginx
spec:
  restartPolicy: OnFailure
  containers:
    - name: test5
      image: nginx:latest
      imagePullPolicy: Always