---
apiVersion: v1
kind: Pod
metadata:
  name: test2
  labels: 
    not-billing: customer1
spec:
  restartPolicy: OnFailure
  containers:
    - name: test2
      image: nginx
      imagePullPolicy: Always