apiVersion: v1
kind: Pod
metadata:
  name: test2-nginx-img-latest
  namespace: nginx
  labels: 
    app: nginx
spec:
  restartPolicy: OnFailure
  containers:
    - name: test2
      image: nginx:latest
      imagePullPolicy: Always