apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: nginx
spec: {}
status: {}
---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: test1
#   namespace: nginx
#   labels:
#     app: nginx
# spec:
#   restartPolicy: OnFailure
#   containers:
#     - name: test1
#       image: nginx:1.17.1
#       imagePullPolicy: Always
# ---
apiVersion: v1
kind: Pod
metadata:
  name: test2
  namespace: nginx
  labels: 
    app: nginx
spec:
  restartPolicy: OnFailure
  containers:
    - name: test2
      image: nginx:latest
      imagePullPolicy: Always
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: test3
#   namespace: nginx
#   labels:
#     app: nginx
# spec:
#   restartPolicy: OnFailure
#   containers:
#     - name: test3
#       image: redis
#       imagePullPolicy: Always