apiVersion: v1
kind: Pod
metadata:
  name: test4-non-nginx-img-default-ns
  namespace: default
  labels:
    app: busybox
spec:
  restartPolicy: OnFailure
  containers:
    - name: test4
      image: busybox
      imagePullPolicy: Always